### ISSUE TITLE
expo-cli 3.11.1 nerfed facebook login.

### ISSUE THREAD

**Issue by SeanRenet** [expo/expo-cli#1351]
## Description

expo-cli 3.11.1 nerfed facebook login.
A hour ago, before upgrading expo-cli this code used to  work perfectly.

			
## Expected Behavior

An hour ago before updating expo-cli this code worked perfectly

`const { type, token } = await Facebook.logInWithReadPermissionsAsync('< my actual facebook project id >', { permissions: ['public_profile', 'email'] }).catch(function(error) {
				// Handle Errors here.
				
        let errorCode = error.code;
        let errorMessage = error.message;
        // The email of the user's account used.
       let email = error.email;
       // The firebase.auth.AuthCredential type that was used.
       let credential = error.credential;
      console.log(errorCode, ' ', errorMessage, ' ', email, ' ', credential, ' ',);

});`	

I also tried Facebook.initializeAsync  but that did not work either

## Observed Behavior
Error from facebook is 
`E_FBLOGIN_APP_ID   Tried to perform Facebook login, but no Facebook app id was provided. Specify Facebook app id in Info.plist. `

error from expo is 
```
undefined is not an object (evaluating '_ref.type')
* src/actions/user.js:82:11 in _callee3$
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:271:30 in invoke
- ... 13 more stack frames from framework internals
```

If I run Facebook.initializeAsync . I get 

`Facebook.initializeAsync is not a function`

## Environment

  Expo CLI 3.11.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 13.2.0 - /usr/local/bin/node
      Yarn: 1.19.2 - /usr/local/bin/yarn
      npm: 6.13.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.1 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.11.1

 "expo-facebook": "~7.0.1",  does not work on ^8.0.0 either

Emulator is iPhone 11 Pro Max 13.3
Phone 1  is Pixel 3 Android version 10
Phone 2 is Samsung S8 Android version 9

## Reproducible Demo

I am not sure how to do this...
