### ISSUE TITLE
Project fails to start after update to 3.11.3

### ISSUE THREAD

**Issue by DanielFloris** [expo/expo-cli#1420]
## Description
After updating to version 3.11.3, my expo project is unable to start. 
## Expected Behavior
`expo start` starts the project.

## Observed Behavior

`expo start` fails with message
```
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
error Cannot find module 'toidentifier'

Metro Bundler process exited with code 1
Error: Metro Bundler process exited with code 1
    at ChildProcess.packagerProcess.once (/@expo/xdl@57.4.3/src/Project.ts:1922:16)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

## Environment

Expo CLI 3.11.3 environment info:
    System:
      OS: Linux 4.4 Ubuntu 18.04.3 LTS (Bionic Beaver)
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 8.10.0 - /usr/bin/node
      Yarn: 1.21.1 - /usr/bin/yarn
      npm: 3.5.2 - /usr/bin/npm
    npmPackages:
      expo: ^36.0.2 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.11.3

- Phone/emulator/simulator platform, model and version:
This is unnecessary, as I can't even get the project started.

## Reproducible Demo
I'm not sure how I would/should supply this?

**Comment by brentvatne** [comment]
what version were you using prior to 3.11.3? this might be an issue on your particular machine - perhaps something when wrong during `npm install` and the `toidentifier` package wasn't installed properly. i'd try uninstalling `expo-cli` and installing it again.

**Comment by EvanBacon** [comment]
Possibly an issue with `react-native-community/cli` as we wrap that process then re-throw errors when it fails. I would imagine reinstalling should work.

More info on where `toidentifier` is coming from:
```
[1/4] 🤔  Why do we have the module "toidentifier"...?
=> Found "toidentifier@1.0.0"
info Reasons this module exists
   - "_project_#raw-body#http-errors" depends on it
   - Hoisted from "_project_#raw-body#http-errors#toidentifier"
   - Hoisted from "_project_#send#http-errors#toidentifier"
   - Hoisted from "_project_#express#body-parser#http-errors#toidentifier"
```

**Comment by DanielFloris** [comment]
FYI, reinstalling expo-cli didn't work for me. I've re-cloned my repo into a new folder and reinstalled everything and am back up and running.
¯\_(ツ)_/¯

**Comment by fson** [comment]
Sounds like this issue is resolved. Please reopen, if the problem comes back.
