### ISSUE TITLE
Cannot find "...image-utils\build\index.js

### ISSUE THREAD

**Issue by TrabajandoIdeas** [expo/expo-cli#758]
I just run the command:
```
yarn global add expo-cli 
expo init project
cd project
expo start
```
And get this error:
```
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Cannot find module 'C:\Users\USERNAME\AppData\Local\Yarn\Data\global\node_modules\@expo\image-utils\build\index.js'. Please verify that the package.json has a valid "main" entry
Set EXPO_DEBUG=true in your env to view the stack trace.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I'm not touch any file. Can someone help me?

**Comment by renatoc8** [comment]
Is this a new project or existing? If it's new, I would check the package.json file and make sure it has a "main" entry, or post your package.json file here.

If the above is not the issue, then I think this is due to a bug introduced by the latest version of expo-cli, see #755

**Comment by chrisdrackett** [comment]
I'm running into this as well after upgrading expo-cli. This is with a new project using `expo init` on expo `2.20.3`

**Comment by crimvod** [comment]
I'm getting the following after upgrading to 2.20.3 as well

`Cannot find module '@expo/image-utils'`

**Comment by cruzach** [comment]
I have a feeling this is the same issue as #755 (as @renatoc8 pointed out), in which case it has been fixed in the most recent release `expo-cli@2.20.5`
